apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: "bluecompute-app-qa"
  name: demo-bluecompute-qa
  namespace: qa
spec:
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
  selector:
    matchLabels:
      app: "bluecompute-app"
status: {}
